export const initialReviewerProfile = {
  reviewer_id: "REV-001",
  full_name: "Preethi Nair",
  role: "Claims Reviewer",
  region: "South India",
  assigned_zones: ["BLR-South", "BLR-North", "CHN-Central"],
  claims_reviewed_today: 14,
  avg_review_time_mins: 4.2,
};

export const initialKpis = {
  pendingQueue: 23,
  approvedToday: 41,
  rejectedToday: 6,
  fraudFlagged: 2,
  reserveRunwayDays: 94,
  zonesActive: 3,
  zonesTotal: 3,
  avgPayout: 284,
  totalPayoutToday: 11644,
};

export const initialClaims = [
  {
    id: "CLM-9824-21",
    driver: "Sudarshan K.",
    tier: "Platinum",
    reason: "Severe Weather",
    amount: 450,
    status: "Pending",
    priority: "High",
    fraudScore: 0.08,
    zone: "BLR-South",
  },
  {
    id: "CLM-7711-08",
    driver: "Dakshina R.",
    tier: "Gold",
    reason: "Heavy Rain",
    amount: 312,
    status: "Pending",
    priority: "High",
    fraudScore: 0.12,
    zone: "BLR-North",
  },
  {
    id: "CLM-5510-44",
    driver: "Sudha M.",
    tier: "Silver",
    reason: "Network Failure",
    amount: 180,
    status: "Pending",
    priority: "Medium",
    fraudScore: 0.09,
    zone: "CHN-Central",
  },
  {
    id: "CLM-9102-54",
    driver: "Sudarshan K.",
    tier: "Platinum",
    reason: "Platform Outage",
    amount: 390,
    status: "Pending",
    priority: "High",
    fraudScore: 0.71,
    zone: "BLR-South",
  },
  {
    id: "CLM-7322-90",
    driver: "Dakshina R.",
    tier: "Gold",
    reason: "Vehicle Breakdown",
    amount: 0,
    status: "Rejected",
    priority: "Low",
    fraudScore: 0.44,
    zone: "BLR-North",
  },
  {
    id: "CLM-5388-19",
    driver: "Sudha M.",
    tier: "Silver",
    reason: "Severe Weather",
    amount: 224,
    status: "Approved",
    priority: "Medium",
    fraudScore: 0.06,
    zone: "CHN-Central",
  },
  {
    id: "CLM-8101-33",
    driver: "Arjun P.",
    tier: "Silver",
    reason: "App Outage",
    amount: 180,
    status: "Pending",
    priority: "Medium",
    fraudScore: 0.15,
    zone: "BLR-South",
  },
  {
    id: "CLM-6623-77",
    driver: "Meena S.",
    tier: "Gold",
    reason: "Waterlogging",
    amount: 312,
    status: "Pending",
    priority: "High",
    fraudScore: 0.19,
    zone: "CHN-Central",
  },
];

export const initialDrivers = [
  {
    name: "Sudarshan K.",
    tier: "Platinum",
    zone: "BLR-South",
    platform: "Swiggy",
    claims: 8,
    riskScore: 0.82,
    totalPayout: 24800,
  },
  {
    name: "Dakshina R.",
    tier: "Gold",
    zone: "BLR-North",
    platform: "Zomato",
    claims: 5,
    riskScore: 0.65,
    totalPayout: 14200,
  },
  {
    name: "Sudha M.",
    tier: "Silver",
    zone: "CHN-Central",
    platform: "Swiggy",
    claims: 3,
    riskScore: 0.48,
    totalPayout: 6400,
  },
  {
    name: "Arjun P.",
    tier: "Silver",
    zone: "BLR-South",
    platform: "Blinkit",
    claims: 2,
    riskScore: 0.51,
    totalPayout: 4100,
  },
  {
    name: "Meena S.",
    tier: "Gold",
    zone: "CHN-Central",
    platform: "Zomato",
    claims: 4,
    riskScore: 0.67,
    totalPayout: 11600,
  },
  {
    name: "Ravi T.",
    tier: "Platinum",
    zone: "BLR-North",
    platform: "Swiggy",
    claims: 9,
    riskScore: 0.79,
    totalPayout: 28300,
  },
];

export const initialAuditLogs = [
  {
    timestamp: "2026-04-26 09:14",
    actor: "Preethi Nair",
    action: "APPROVED",
    target: "CLM-5388-19",
    details: "₹224, Severe Weather",
  },
  {
    timestamp: "2026-04-26 09:02",
    actor: "Preethi Nair",
    action: "REJECTED",
    target: "CLM-7322-90",
    details: "₹0, Vehicle Breakdown — outside zone",
  },
  {
    timestamp: "2026-04-25 17:41",
    actor: "System",
    action: "AUTO-APPROVED",
    target: "CLM-8833-12",
    details: "₹247, oracle 3/4 consensus",
  },
  {
    timestamp: "2026-04-25 16:22",
    actor: "Preethi Nair",
    action: "REJECTED",
    target: "CLM-9102-54",
    details: "fraud score 0.71 — Rejected",
  },
  {
    timestamp: "2026-04-25 14:09",
    actor: "Preethi Nair",
    action: "APPROVED",
    target: "CLM-6101-88",
    details: "₹312, Heavy Rain",
  },
];
