function daysAgo(n: number, time: string): string {
  const dt = new Date();
  dt.setDate(dt.getDate() - n);
  const y = dt.getFullYear();
  const m = String(dt.getMonth() + 1).padStart(2, "0");
  const d = String(dt.getDate()).padStart(2, "0");
  return `${y}-${m}-${d} ${time}`;
}

export const initialReviewerProfile = {
  reviewer_id: "REV-001",
  full_name: "Preethi Nair",
  role: "Claims Reviewer",
  region: "South & East India",
  assigned_zones: ["BLR-South", "BLR-North", "CHN-Central", "KOL-South"],
  claims_reviewed_today: 14,
  avg_review_time_mins: 4.2,
};

export const initialKpis = {
  pendingQueue: 23,
  approvedToday: 41,
  rejectedToday: 6,
  fraudFlagged: 2,
  reserveRunwayDays: 94,
  zonesActive: 3,
  zonesTotal: 3,
  avgPayout: 284,
  totalPayoutToday: 11644,
};

export const initialClaims = [
  {
    id: "CLM-9824-21",
    driver: "Sudarshan K.",
    tier: "Platinum",
    reason: "Severe Weather",
    description: "Heavy flooding in Koramangala disrupted all deliveries for 4 hours.",
    amount: 450,
    status: "Pending",
    priority: "High",
    fraudScore: 0.08,
    zone: "BLR-South",
    justification: "",
    submittedAt: daysAgo(0, "08:30"),
    isFraud: false,
  },
  {
    id: "CLM-7711-08",
    driver: "Dakshina Moorthy",
    tier: "Gold",
    reason: "Heavy Rain",
    description: "Anna Nagar roads waterlogged — no deliveries possible from 3pm to 7pm.",
    amount: 312,
    status: "Pending",
    priority: "High",
    fraudScore: 0.12,
    zone: "CHN-Central",
    justification: "",
    submittedAt: daysAgo(0, "07:50"),
    isFraud: false,
  },
  {
    id: "CLM-5510-44",
    driver: "Sudha P.",
    tier: "Silver",
    reason: "Network Failure",
    description: "Swiggy app showing connection errors, no order assignments for 2 hours.",
    amount: 180,
    status: "Pending",
    priority: "Medium",
    fraudScore: 0.09,
    zone: "KOL-South",
    justification: "",
    submittedAt: daysAgo(1, "18:10"),
    isFraud: false,
  },
  {
    id: "CLM-9102-54",
    driver: "Sudarshan K.",
    tier: "Platinum",
    reason: "Platform Outage",
    description: "Zomato backend down — no orders for 3 hours. Zero income window.",
    amount: 390,
    status: "Pending",
    priority: "High",
    fraudScore: 0.71,
    zone: "BLR-South",
    justification: "",
    submittedAt: daysAgo(1, "15:45"),
    isFraud: true,
  },
  {
    id: "CLM-7322-90",
    driver: "Dakshina Moorthy",
    tier: "Gold",
    reason: "Vehicle Breakdown",
    amount: 0,
    description: "Bike engine failure at Vadapalani. Could not complete shift.",
    status: "Rejected",
    priority: "Low",
    fraudScore: 0.44,
    zone: "CHN-Central",
    justification: "GPS proximity log shows worker outside disruption zone.",
    submittedAt: daysAgo(2, "14:00"),
    isFraud: false,
  },
  {
    id: "CLM-5388-19",
    driver: "Sudha P.",
    tier: "Silver",
    reason: "Severe Weather",
    description: "Cyclone warning — Ballygunge area inaccessible due to waterlogging.",
    amount: 224,
    status: "Approved",
    priority: "Medium",
    fraudScore: 0.06,
    zone: "KOL-South",
    justification: "Oracle consensus confirmed. IMD red alert active.",
    submittedAt: daysAgo(2, "10:30"),
    isFraud: false,
  },
  {
    id: "CLM-8101-33",
    driver: "Arjun P.",
    tier: "Silver",
    reason: "App Outage",
    description: "Blinkit app unresponsive for entire morning shift. Screenshot attached.",
    amount: 180,
    status: "Pending",
    priority: "Medium",
    fraudScore: 0.15,
    zone: "BLR-South",
    justification: "",
    submittedAt: daysAgo(0, "09:00"),
    isFraud: false,
  },
  {
    id: "CLM-6623-77",
    driver: "Meena S.",
    tier: "Gold",
    reason: "Waterlogging",
    description: "Adyar area completely flooded. Stuck for 5 hours with no deliveries.",
    amount: 312,
    status: "Pending",
    priority: "High",
    fraudScore: 0.19,
    zone: "CHN-Central",
    justification: "",
    submittedAt: daysAgo(0, "06:45"),
    isFraud: false,
  },
];

export const initialDrivers = [
  {
    name: "Sudarshan K.",
    tier: "Platinum",
    zone: "BLR-South",
    platform: "Swiggy + Zomato",
    claims: 8,
    riskScore: 0.82,
    totalPayout: 24800,
  },
  {
    name: "Dakshina Moorthy",
    tier: "Gold",
    zone: "CHN-Central",
    platform: "Swiggy + Zomato",
    claims: 6,
    riskScore: 0.65,
    totalPayout: 18400,
  },
  {
    name: "Sudha P.",
    tier: "Silver",
    zone: "KOL-South",
    platform: "Swiggy",
    claims: 3,
    riskScore: 0.48,
    totalPayout: 9200,
  },
  {
    name: "Arjun P.",
    tier: "Silver",
    zone: "BLR-South",
    platform: "Blinkit",
    claims: 2,
    riskScore: 0.51,
    totalPayout: 4100,
  },
  {
    name: "Meena S.",
    tier: "Gold",
    zone: "CHN-Central",
    platform: "Zomato",
    claims: 4,
    riskScore: 0.67,
    totalPayout: 11600,
  },
  {
    name: "Ravi T.",
    tier: "Platinum",
    zone: "BLR-North",
    platform: "Swiggy",
    claims: 9,
    riskScore: 0.79,
    totalPayout: 28300,
  },
];

export const initialAuditLogs = [
  {
    timestamp: daysAgo(0, "09:14"),
    actor: "Preethi Nair",
    action: "APPROVED",
    target: "CLM-5388-19",
    details: "₹224, Severe Weather — oracle consensus confirmed",
  },
  {
    timestamp: daysAgo(0, "09:02"),
    actor: "Preethi Nair",
    action: "REJECTED",
    target: "CLM-7322-90",
    details: "₹0, Vehicle Breakdown — outside disruption zone",
  },
  {
    timestamp: daysAgo(1, "17:41"),
    actor: "System",
    action: "AUTO-APPROVED",
    target: "CLM-8833-12",
    details: "₹247, oracle 3/4 consensus (IMD + AccuWeather + NASA-GPM)",
  },
  {
    timestamp: daysAgo(1, "16:22"),
    actor: "Preethi Nair",
    action: "REJECTED",
    target: "CLM-9102-54",
    details: "fraud score 0.71 — isolation-forest anomaly detected",
  },
  {
    timestamp: daysAgo(1, "14:09"),
    actor: "Preethi Nair",
    action: "APPROVED",
    target: "CLM-6101-88",
    details: "₹312, Heavy Rain — CHN-Central",
  },
];
